/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsoleRouteImport } from './routes/console'
import { Route as DetectRouteImport } from './routes/detect'
import { Route as ExitRouteImport } from './routes/exit'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ImpactRouteImport } from './routes/impact'
import { Route as IndiaRouteImport } from './routes/india'
import { Route as IntelligenceRouteImport } from './routes/intelligence'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ReportRouteImport } from './routes/report'
import { Route as SupportRouteImport } from './routes/support'
import { Route as TrustedAdultRouteImport } from './routes/trusted-adult'
import { Route as ConsoleIndexRouteImport } from './routes/console/index'
import { Route as ConsoleAnalyticsRouteImport } from './routes/console/analytics'
import { Route as ConsoleArchitectureRouteImport } from './routes/console/architecture'
import { Route as ConsoleAuditRouteImport } from './routes/console/audit'
import { Route as ConsoleSettingsRouteImport } from './routes/console/settings'
import { Route as ReportDoneRouteImport } from './routes/report.done'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ConsoleCasesCaseIdRouteImport } from './routes/console/cases.$caseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleRoute = ConsoleRouteImport.update({
  id: '/console',
  path: '/console',
  getParentRoute: () => rootRouteImport,
} as any)
const DetectRoute = DetectRouteImport.update({
  id: '/detect',
  path: '/detect',
  getParentRoute: () => rootRouteImport,
} as any)
const ExitRoute = ExitRouteImport.update({
  id: '/exit',
  path: '/exit',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactRoute = ImpactRouteImport.update({
  id: '/impact',
  path: '/impact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndiaRoute = IndiaRouteImport.update({
  id: '/india',
  path: '/india',
  getParentRoute: () => rootRouteImport,
} as any)
const IntelligenceRoute = IntelligenceRouteImport.update({
  id: '/intelligence',
  path: '/intelligence',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const TrustedAdultRoute = TrustedAdultRouteImport.update({
  id: '/trusted-adult',
  path: '/trusted-adult',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleIndexRoute = ConsoleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleAnalyticsRoute = ConsoleAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleArchitectureRoute = ConsoleArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleAuditRoute = ConsoleAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => ConsoleRoute,
} as any)
const ConsoleSettingsRoute = ConsoleSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ConsoleRoute,
} as any)
const ReportDoneRoute = ReportDoneRouteImport.update({
  id: '/done',
  path: '/done',
  getParentRoute: () => ReportRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsoleCasesCaseIdRoute = ConsoleCasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => ConsoleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteWithChildren
  '/detect': typeof DetectRoute
  '/exit': typeof ExitRoute
  '/help': typeof HelpRoute
  '/impact': typeof ImpactRoute
  '/india': typeof IndiaRoute
  '/intelligence': typeof IntelligenceRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRouteWithChildren
  '/support': typeof SupportRoute
  '/trusted-adult': typeof TrustedAdultRoute
  '/console/analytics': typeof ConsoleAnalyticsRoute
  '/console/architecture': typeof ConsoleArchitectureRoute
  '/console/audit': typeof ConsoleAuditRoute
  '/console/settings': typeof ConsoleSettingsRoute
  '/report/done': typeof ReportDoneRoute
  '/console/': typeof ConsoleIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/console/cases/$caseId': typeof ConsoleCasesCaseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/detect': typeof DetectRoute
  '/exit': typeof ExitRoute
  '/help': typeof HelpRoute
  '/impact': typeof ImpactRoute
  '/india': typeof IndiaRoute
  '/intelligence': typeof IntelligenceRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRouteWithChildren
  '/support': typeof SupportRoute
  '/trusted-adult': typeof TrustedAdultRoute
  '/console/analytics': typeof ConsoleAnalyticsRoute
  '/console/architecture': typeof ConsoleArchitectureRoute
  '/console/audit': typeof ConsoleAuditRoute
  '/console/settings': typeof ConsoleSettingsRoute
  '/report/done': typeof ReportDoneRoute
  '/console': typeof ConsoleIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/console/cases/$caseId': typeof ConsoleCasesCaseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/console': typeof ConsoleRouteWithChildren
  '/detect': typeof DetectRoute
  '/exit': typeof ExitRoute
  '/help': typeof HelpRoute
  '/impact': typeof ImpactRoute
  '/india': typeof IndiaRoute
  '/intelligence': typeof IntelligenceRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRouteWithChildren
  '/support': typeof SupportRoute
  '/trusted-adult': typeof TrustedAdultRoute
  '/console/analytics': typeof ConsoleAnalyticsRoute
  '/console/architecture': typeof ConsoleArchitectureRoute
  '/console/audit': typeof ConsoleAuditRoute
  '/console/settings': typeof ConsoleSettingsRoute
  '/report/done': typeof ReportDoneRoute
  '/console/': typeof ConsoleIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/console/cases/$caseId': typeof ConsoleCasesCaseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/console'
    | '/detect'
    | '/exit'
    | '/help'
    | '/impact'
    | '/india'
    | '/intelligence'
    | '/login'
    | '/privacy'
    | '/report'
    | '/support'
    | '/trusted-adult'
    | '/console/analytics'
    | '/console/architecture'
    | '/console/audit'
    | '/console/settings'
    | '/report/done'
    | '/console/'
    | '/api/auth/$'
    | '/console/cases/$caseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/detect'
    | '/exit'
    | '/help'
    | '/impact'
    | '/india'
    | '/intelligence'
    | '/login'
    | '/privacy'
    | '/report'
    | '/support'
    | '/trusted-adult'
    | '/console/analytics'
    | '/console/architecture'
    | '/console/audit'
    | '/console/settings'
    | '/report/done'
    | '/console'
    | '/api/auth/$'
    | '/console/cases/$caseId'
  id:
    | '__root__'
    | '/'
    | '/console'
    | '/detect'
    | '/exit'
    | '/help'
    | '/impact'
    | '/india'
    | '/intelligence'
    | '/login'
    | '/privacy'
    | '/report'
    | '/support'
    | '/trusted-adult'
    | '/console/analytics'
    | '/console/architecture'
    | '/console/audit'
    | '/console/settings'
    | '/report/done'
    | '/console/'
    | '/api/auth/$'
    | '/console/cases/$caseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsoleRoute: typeof ConsoleRouteWithChildren
  DetectRoute: typeof DetectRoute
  ExitRoute: typeof ExitRoute
  HelpRoute: typeof HelpRoute
  ImpactRoute: typeof ImpactRoute
  IndiaRoute: typeof IndiaRoute
  IntelligenceRoute: typeof IntelligenceRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ReportRoute: typeof ReportRouteWithChildren
  SupportRoute: typeof SupportRoute
  TrustedAdultRoute: typeof TrustedAdultRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console': {
      id: '/console'
      path: '/console'
      fullPath: '/console'
      preLoaderRoute: typeof ConsoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/detect': {
      id: '/detect'
      path: '/detect'
      fullPath: '/detect'
      preLoaderRoute: typeof DetectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exit': {
      id: '/exit'
      path: '/exit'
      fullPath: '/exit'
      preLoaderRoute: typeof ExitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact': {
      id: '/impact'
      path: '/impact'
      fullPath: '/impact'
      preLoaderRoute: typeof ImpactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/india': {
      id: '/india'
      path: '/india'
      fullPath: '/india'
      preLoaderRoute: typeof IndiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/intelligence': {
      id: '/intelligence'
      path: '/intelligence'
      fullPath: '/intelligence'
      preLoaderRoute: typeof IntelligenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trusted-adult': {
      id: '/trusted-adult'
      path: '/trusted-adult'
      fullPath: '/trusted-adult'
      preLoaderRoute: typeof TrustedAdultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/': {
      id: '/console/'
      path: '/'
      fullPath: '/console/'
      preLoaderRoute: typeof ConsoleIndexRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/analytics': {
      id: '/console/analytics'
      path: '/analytics'
      fullPath: '/console/analytics'
      preLoaderRoute: typeof ConsoleAnalyticsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/architecture': {
      id: '/console/architecture'
      path: '/architecture'
      fullPath: '/console/architecture'
      preLoaderRoute: typeof ConsoleArchitectureRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/audit': {
      id: '/console/audit'
      path: '/audit'
      fullPath: '/console/audit'
      preLoaderRoute: typeof ConsoleAuditRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/console/settings': {
      id: '/console/settings'
      path: '/settings'
      fullPath: '/console/settings'
      preLoaderRoute: typeof ConsoleSettingsRouteImport
      parentRoute: typeof ConsoleRoute
    }
    '/report/done': {
      id: '/report/done'
      path: '/done'
      fullPath: '/report/done'
      preLoaderRoute: typeof ReportDoneRouteImport
      parentRoute: typeof ReportRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/console/cases/$caseId': {
      id: '/console/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/console/cases/$caseId'
      preLoaderRoute: typeof ConsoleCasesCaseIdRouteImport
      parentRoute: typeof ConsoleRoute
    }
  }
}

interface ConsoleRouteChildren {
  ConsoleAnalyticsRoute: typeof ConsoleAnalyticsRoute
  ConsoleArchitectureRoute: typeof ConsoleArchitectureRoute
  ConsoleAuditRoute: typeof ConsoleAuditRoute
  ConsoleSettingsRoute: typeof ConsoleSettingsRoute
  ConsoleIndexRoute: typeof ConsoleIndexRoute
  ConsoleCasesCaseIdRoute: typeof ConsoleCasesCaseIdRoute
}

const ConsoleRouteChildren: ConsoleRouteChildren = {
  ConsoleAnalyticsRoute: ConsoleAnalyticsRoute,
  ConsoleArchitectureRoute: ConsoleArchitectureRoute,
  ConsoleAuditRoute: ConsoleAuditRoute,
  ConsoleSettingsRoute: ConsoleSettingsRoute,
  ConsoleIndexRoute: ConsoleIndexRoute,
  ConsoleCasesCaseIdRoute: ConsoleCasesCaseIdRoute,
}

const ConsoleRouteWithChildren =
  ConsoleRoute._addFileChildren(ConsoleRouteChildren)

interface ReportRouteChildren {
  ReportDoneRoute: typeof ReportDoneRoute
}

const ReportRouteChildren: ReportRouteChildren = {
  ReportDoneRoute: ReportDoneRoute,
}

const ReportRouteWithChildren =
  ReportRoute._addFileChildren(ReportRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsoleRoute: ConsoleRouteWithChildren,
  DetectRoute: DetectRoute,
  ExitRoute: ExitRoute,
  HelpRoute: HelpRoute,
  ImpactRoute: ImpactRoute,
  IndiaRoute: IndiaRoute,
  IntelligenceRoute: IntelligenceRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ReportRoute: ReportRouteWithChildren,
  SupportRoute: SupportRoute,
  TrustedAdultRoute: TrustedAdultRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
